// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int tests = Integer.parseInt(args[0]);
		int larger = 0, smaller = 0;
		while (tests>0) {
			if (Math.random()>0.5) {
				larger += 1;
			}
			else {
				smaller += 1;
			}
			tests -= 1;
		}
		System.out.println("> 0.5:  " + larger + " times");
		System.out.println("<= 0.5: " + smaller + " times");
		if (smaller>0) {
			System.out.println("ratio:  " + (double) larger/smaller);	
		}
	}
}
